# Generated by Django 3.2.4 on 2021-08-13 18:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50, verbose_name='User Name')),
                ('password', models.CharField(db_index=True, max_length=15, verbose_name='Password')),
                ('email', models.EmailField(db_index=True, max_length=100, verbose_name='Email')),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Picture')),
                ('token', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Token')),
                ('token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Token Expiration Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=15, verbose_name='Gender')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
