# Generated by Django 3.2.4 on 2021-08-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(db_index=True, max_length=15, verbose_name='Gender'),
        ),
    ]
