# Generated by Django 3.2.4 on 2021-08-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('receive_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_recieve_user_id', to='users.user')),
                ('send_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_send_user_id', to='users.user')),
            ],
            options={
                'db_table': 'like',
            },
        ),
    ]
