# Generated by Django 3.2.4 on 2021-08-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='receive_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_recieve_like_user_id', to='users.user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='send_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_send_like_user_id', to='users.user'),
        ),
    ]
